/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: CommonData.h
  Source: /home/centrix/Code/dds/bin/CommonData.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_COMMONDATA_H_C9CA2266916623B599A6CDD77CB6A4B2
#define DDSC_COMMONDATA_H_C9CA2266916623B599A6CDD77CB6A4B2

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CommonData_Data
{
  int32_t no;
  char * context;
} CommonData_Data;

extern const dds_topic_descriptor_t CommonData_Data_desc;

#define CommonData_Data__alloc() \
((CommonData_Data*) dds_alloc (sizeof (CommonData_Data)));

#define CommonData_Data_free(d,o) \
dds_sample_free ((d), &CommonData_Data_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_COMMONDATA_H_C9CA2266916623B599A6CDD77CB6A4B2 */
