#ifndef _SOMEIP_CFG_H
#define _SOMEIP_CFG_H
/* ================================ [ MACROS    ] ============================================== */
#define SOMEIP_SSID_CLIENT0 0
#define SOMEIP_CSID_SERVER0 1

#define SOMEIP_RX_PID_SOMEIP_CLIENT0 1
#define SOMEIP_TX_PID_SOMEIP_CLIENT0 1
#define SOMEIP_RX_PID_SOMEIP_SERVER0 0
#define SOMEIP_TX_PID_SOMEIP_SERVER0 0

#define SOMEIP_RX_METHOD_SERVER0_METHOD1 0

#define SOMEIP_TX_METHOD_CLIENT0_METHOD2 0 //TxMethodId

#define SOMEIP_TX_EVT_CLIENT0_EVENT_GROUP2_EVENT0 0

#define SOMEIP_RX_EVT_SERVER0_EVENT_GROUP1_EVENT0 0

#define SOMEIP_MAIN_FUNCTION_PERIOD 10
#define SOMEIP_CONVERT_MS_TO_MAIN_CYCLES(x) \
  ((x + SOMEIP_MAIN_FUNCTION_PERIOD - 1) / SOMEIP_MAIN_FUNCTION_PERIOD)
#endif 